### ISSUE TITLE
Converting a track to an actual URI might cause unhanded exceptions

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-beets#13]
By the look of https://github.com/mopidy/mopidy-beets/blob/master/mopidy_beets/actor.py#L37 the code won't nicely handle an invalid track ID. This should be fixed so the code returns None in such cases.

**Comment by sumpfralle** [comment]
thank you for pointing out this issue!
Commit 471dac7955900af9a12985db314d980ac1f93204 fixed this problem.
