### ISSUE TITLE
Incorrect search results

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy-beets#4]
The search results are a little strange.

Using the mpd frontend, 
'search artist "Can"' 
returns all tracks with 'can' in them - either the artist name, album name, or track name. This might just be a limitation of beets I think but can you confirm this?

Using the Mopidy HTTP frontend however, I get unusual results - 
mopidy.library.search({artist: 'Can'}, ['beets:'])
returns an object with a uri property of 'beets:search-C', which contains every artist beginning with 'A', 'B', or 'C'.

Mopidy 0.14.2 (Ubuntu ppa), and the latest beets and mopidy-beets installed from pip (yesterday).

**Comment by sumpfralle** [comment]
thank you for your hint!
Now the search code should work fine for the different categories.
